#!/usr/bin/env node
/**
 * Extracts question data from the original HTML file
 * Run: node scripts/extract.cjs
 */
const fs = require('fs');
const path = require('path');
const { parse } = require('node-html-parser');

const SRC = path.join(__dirname, '../../data/source-html/PHYS1204_ExamBank_Interactive.html');
const OUT = path.join(__dirname, '../src/data/questions.js');

console.log('Reading HTML...');
const html = fs.readFileSync(SRC, 'utf-8');

console.log('Parsing...');
const root = parse(html);

const topics = [];

root.querySelectorAll('.topic-section').forEach(section => {
  const id = section.getAttribute('id') || '';
  const titleEl = section.querySelector('.topic-title');
  const numEl = section.querySelector('.topic-num');
  const title = titleEl ? titleEl.text.trim() : id;
  const topicNum = numEl ? numEl.text.trim() : '';

  const questions = [];

  section.querySelectorAll('.q-card').forEach((card, i) => {
    const numSpan = card.querySelector('.q-num');
    const textSpan = card.querySelector('.q-text');
    const marksSpan = card.querySelector('.q-marks');
    const answerDiv = card.querySelector('.q-answer');
    const advanced = card.classList.contains('advanced');

    const num = numSpan ? numSpan.text.trim() : `Q${i + 1}`;
    const textHtml = textSpan ? textSpan.innerHTML : '';
    const marksText = marksSpan ? marksSpan.text.trim() : '4 marks';
    const marks = parseInt(marksText) || 4;
    const answerHtml = answerDiv ? answerDiv.innerHTML : '';

    // Generate stable ID
    const qid = 'qid_' + num.replace(/\s+/g, '');

    questions.push({ qid, num, textHtml, marks, answerHtml, advanced });
  });

  if (questions.length) {
    topics.push({ id, topicNum, title, questions });
  }
});

const totalQ = topics.reduce((s, t) => s + t.questions.length, 0);
console.log(`Extracted ${topics.length} topics, ${totalQ} questions.`);

const output = `// Auto-generated by scripts/extract.cjs - do not edit manually
export const topics = ${JSON.stringify(topics, null, 2)};

export const allQuestions = topics.flatMap(t =>
  t.questions.map(q => ({ ...q, topicId: t.id, topicTitle: t.title }))
);
`;

fs.writeFileSync(OUT, output, 'utf-8');
console.log(`Written to ${OUT} (${(fs.statSync(OUT).size / 1024).toFixed(0)} KB)`);
